### ISSUE TITLE
The mount's speed is abnormal

### ISSUE THREAD

**Issue by wangyu2333333** [quentin452/The-Lord-of-the-Rings#28]
The mount's speed is abnormal and too slow(When the player is riding it),This issue has been present since v36.16,This issue also exists when only the mod itself is installed

https://github.com/quentin452/The-Lord-of-the-Rings/assets/121626899/4f8a0bfa-fe08-43a5-b261-6c9be493a748

**Comment by Mcayear** [comment]
I am aware of this issue and it has been resolved.

fix version download: https://pan.9991565.xyz/AliyunDrive/lotr/mods/lotr-v36.29-giteeMain.9+fb2c9f2fea-dirty.jar

open source repo: https://gitee.com/ayear/The-Lord-of-the-Rings

**Comment by quentin452** [comment]
should be fixed in V36.30
